### ISSUE TITLE
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

### ISSUE THREAD

**Issue by kangsudal** [kangsudal/kkunglegram_practice#1]
======== Exception caught by widgets library =======================================================
The following FirebaseException was thrown building Container:
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

The relevant error-causing widget was: 
  Container Container:file:///C:/Users/kangs/AndroidStudioProjects/kkunglegram_practice/lib/screens/authenticate/authenticate.dart:9:12
When the exception was thrown, this was the stack: 
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:193:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:53:41)
#2      FirebaseAuth.instance (package:firebase_auth/src/firebase_auth.dart:38:47)
#3      new AuthService (package:kkunglegram_practice/services/auth.dart:6:43)
#4      new _SignInState (package:kkunglegram_practice/screens/authenticate/sign_in.dart:13:29)
#5      SignIn.createState (package:kkunglegram_practice/screens/authenticate/sign_in.dart:8:34)
#6      new StatefulElement (package:flutter/src/widgets/framework.dart:4891:25)
#7      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:758:38)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3812:42)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#12     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#25     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================

**Comment by kangsudal** [comment]
https://firebase.google.com/docs/auth/flutter/start
```
Future<void> main() async {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();

// Ideal time to initialize
await FirebaseAuth.instance.useAuthEmulator('localhost', 9099);
//...
}
```
